import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Navbar } from "@/components";
import { NavBar } from "@/lib/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const navlinks: NavBar[] = [
        {
            id: 1,
            link: "#",
            text: "explore",
        },
        {
            id: 2,
            link: "/",
            text: "problems",
        },
        {
            id: 3,
            link: "#",
            text: "mock",
        },
        {
            id: 4,
            link: "#",
            text: "contests",
        },
        {
            id: 5,
            link: "#",
            text: "acticles",
        },
        {
            id: 6,
            link: "#",
            text: "discuss",
        },
        {
            id: 7,
            link: "/login",
            text: "login",
        },
        {
            id: 8,
            link: "/register",
            text: "register",
        }];

    return (
        <div className="h-screen flex flex-col">
            <Navbar navlinks={navlinks} />
            <div className="flex-1" >{children}</div>
        </div>
    );
}
