import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { NavBar } from "@/lib/types";
import { SideBar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const navlinks: NavBar[] = [
        {
            id: 1,
            link: "/admin",
            text: "Edit Problems",
        },
        ];

    return (
        <div className="h-screen flex">
            <SideBar navlinks={navlinks} />
            <div className="flex-1">{children}</div>
        </div>
    );
}
